vim.keymap.set("n", "-", "<cmd>Oil --float<CR>", { desc = "Open the oil file explorer" })

vim.keymap.set("n", "gl", function()
	vim.diagnostic.open_float()
end, { desc = "Open vim diagnostics floating window" })

vim.keymap.set("n", "<leader>cf", function()
	require("conform").format({ lsp_format = "fallback" })
end, { desc = "Format the current file" })

local harpoon = require("harpoon")

harpoon.setup()

vim.keymap.set("n", "<leader>ha", function()
	harpoon:list():add()
end, { desc = "Add the current file to the harpoon list" })
vim.keymap.set("n", "<leader>h", function()
	harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = "Show all harpooned items" })
vim.keymap.set("n", "<leader>j", function()
	harpoon:list():select(1)
end, { desc = "Select the first item in the harpoon list." })
vim.keymap.set("n", "<leader>k", function()
	harpoon:list():select(2)
end, { desc = "Select the second item in the harpoon list." })
vim.keymap.set("n", "<leader>l", function()
	harpoon:list():select(3)
end, { desc = "Select the third item in the harpoon list." })
vim.keymap.set("n", "<leader>;", function()
	harpoon:list():select(4)
end, { desc = "Select the fourth item in the harpoon list." })
